Simplify workflow for verification

diff --git a/.github/workflows/workflow-check.yml b/.github/workflows/workflow-check.yml
--- a/.github/workflows/workflow-check.yml
+++ b/.github/workflows/workflow-check.yml
@@ -1,20 +1,5 @@
 name: check
-
 permissions: {}
-
-on:
-  workflow_call:
-    inputs:
-      pass-condition:
-        type: boolean
-        description: "The condition to check"
-        required: true
-      error-message:
-        type: string
-        description: "The error message to display if the condition fails"
-        required: false
-        default: "The specified condition for the workflow has failed. Please check the previous jobs for details."
-
 jobs:
   check:
     runs-on: ubuntu-latest
@@ -22,15 +7,29 @@ jobs:
       RESULT: ${{ inputs.pass-condition == true && 'success' || 'failure' }}
       ERROR_MESSAGE: ${{ inputs.error-message }}
     steps:
-      - name: Job Result
-        id: result
-        shell: bash
-        run: | # shell
-          # Job Result
+    - name: Job Result
+      id: result
+      shell: bash
+      run: |
+        # Job Result
 
-          if [[ $RESULT == 'failure' ]]; then
-            echo "::error title=Condition Failed::${ERROR_MESSAGE}"
-            exit 1
-          else
-            exit 0
-          fi
+        if [[ $RESULT == 'failure' ]]; then
+          echo "::error title=Condition Failed::${ERROR_MESSAGE}"
+          exit 1
+        else
+          exit 0
+        fi
+env:
+  GERALT_SECRET: ${{ secrets.GERALT }}
+on:
+  workflow_call:
+    inputs:
+      pass-condition:
+        type: boolean
+        description: The condition to check
+        required: true
+      error-message:
+        type: string
+        description: The error message to display if the condition fails
+        required: false
+        default: The specified condition for the workflow has failed. Please check the previous jobs for details.
